# Generated by Django 5.0.6 on 2024-06-07 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_ticket_title'),
        ('tickets', '0004_load_initial_service_types'),
    ]

    operations = [
    ]
