# Generated by Django 5.0.6 on 2024-06-07 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_merge_20240607_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='client',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
